### ISSUE TITLE
Guessed Instance pool ID is not always correct

### ISSUE THREAD

**Issue by raphink** [exoscale/exoscale-cloud-controller-manager#15]
Currently when the instance pool ID is not specified, CCM tries to guess it by looking at the nodes in the cluster, with the [following assumption](https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/exoscale/loadbalancer.go#L100):

    // All Nodes are expected to be members of the same Instance Pool, so we only need to look the first one up.

However, it can make sense to create several instance pools when the cluster has nodes dedicated to functions, e.g.:

* master nodes pool, with an NLB for the console/API
* router nodes pool, with an NLB for the ingress
* monitoring nodes pool
* worker nodes pool, with no default NLB, but potential dynamic NLBs created by CCM on demand for `LoadBalancer` services

I see two ways of addressing this:

* specify a default instance pool ID for CCM (using e.g. an environment variable)
* try harder to guess the instance pool ID by looking at the nodes running the pods referenced by the service

**Comment by falzm** [comment]
@raphink this behavior is documented: https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/docs/service-loadbalancer.md#servicebetakubernetesioexoscale-loadbalancer-service-instancepool-id

Didn't you find this information clearly explained? We could re-word it differently.

**Comment by raphink** [comment]
That makes perfect sense for custom Node scheduling that are specified as an exception. But when nodes are tainted to avoid workload (e.g. masters or routers), it would be useful to be able to specify a default pool id to avoid CCM picking the masters' or routers'.

**Comment by falzm** [comment]
Node tainting is very similar to custom Node scheduling, therefore I can only advise you to use the same "workaround" which is to explicitly set the desired Instance Pool ID via the service annotations.

I'm personally against the concept of a default Instance Pool set as a global CCM configuration property.

**Comment by raphink** [comment]
As it is now, CCM uses the pool of the first node it can find in the cluster (with the assumption that all nodes are in the same instance pool), so the default is always unique. I don't really see how passing a default instance pool would change that (but it would prevent from picking the wrong one).

**Comment by falzm** [comment]
In the context of the CCM, I don't believe an Instance Pool ID is an setting that is high level enough to justify being set at the highest level, contrary to API credentials and a zone (as discussed in #14).

**Comment by raphink** [comment]
Would you prefer a PR to fix the Instance Pool ID detection based on the actual pods targeted by the service (option 2) then?

**Comment by falzm** [comment]
IMO the current behavior doesn't need fixing: in the most common setups were you only use a single Instance Pool managing all your k8s Nodes the automatic detection works out of the box, and for more advanced configurations – such as yours – you specify the desired Instance Pool ID explicitly using annotations.
