### ISSUE TITLE
Multiple ports don't work as expected

### ISSUE THREAD

**Issue by raphink** [exoscale/exoscale-cloud-controller-manager#16]
From the [documentation](https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/docs/service-loadbalancer.md#kubernetes-services-with-exoscale-network-load-balancers):

> If you declare multiple items in the ports list, each of those will result in a NLB service located on the same NLB instance: this means that although each k8s Service port will be exposed on a dedicated network port (TCP or UDP, depending on the configuration specified), all will share the same NLB Elastic IP address.

However, this is not what happens when multiple ports are specified, e.g.:

```yaml
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8443
```

This will fail to create an NLB. With the current code, when specifying multiple ports, CCM will look for ports named `service` and `healthcheck` and set only the former as an NLB service, using the latter as healthcheck:

https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/exoscale/loadbalancer.go#L453-L461

For this reason, the provided example results in `protocol` being an empty string on line 468, resulting in the following error:

```
I0812 11:37:28.584212       1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"rio-system", Name:"gateway-proxy", UID:"498568fc-1f07-498f-9b62-ad2212aaa0bf", APIVersion:"v1", ResourceVersion:"448886", FieldPath:""}): type: 'Warning' reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: only TCP is supported as service port protocol
```

**Comment by falzm** [comment]
Well that's our bad, indeed the documentation is wrong 😅
It is not possible to have multiple ports defined on the same service of type `LoadBalancer` when using the Exoscale CCM, as per this other (correct) section of the documentation: https://github.com/exoscale/exoscale-cloud-controller-manager/blob/master/docs/service-loadbalancer.md#alternative-exoscale-nlb-service-health-checking-port

I'll go ahead and fix this right away, thank you for reporting this and apologies for the confusion...

**Comment by raphink** [comment]
Isn't the multiple port support a standard? It seems more likely that people would want that feature than a healthcheck on a different port.

**Comment by falzm** [comment]
I don't know if this is a "standard", but for technical reasons we cannot map more than one k8s Service port to an Exoscale NLB service as the annotations used for NLB service configuration only apply to a single NLB service.

**Comment by falzm** [comment]
Fixed in a15b8d30f295fe96cbedd3501fc2d8b8577dca5c.

**Comment by raphink** [comment]
I don't think https://github.com/exoscale/exoscale-cloud-controller-manager/commit/a15b8d30f295fe96cbedd3501fc2d8b8577dca5c  fixes this issue. My example will still produce nonsensical logs because of the bug in the loop, where `protocol` ends up being empty when checking which protocol to redirect.

I personally believe the current behavior is broken. Many standard helm charts or tools (e.g. [rio](https://rio.io/)) rely on `LoadBalancer` services with multiple ports, and I can't think of a case when a developer would expect the currently displayed behavior.

Could you explain the technical reasons that would prevent from mapping multiple NLB services to multiple k8s service ports please?

**Comment by falzm** [comment]
I answered this question in this comment: https://github.com/exoscale/exoscale-cloud-controller-manager/issues/16#issuecomment-672922325

If we were to map the k8s *Service Ports* 1:1 to Exoscale NLB services, the manifest annotations would apply to all the NLB services created, which is not necessarily something we want.

**Comment by raphink** [comment]
Thanks for clarifying. I'm not convinced that preventing multiple ports is more useful than multiple ports getting the same default settings.

**Comment by falzm** [comment]
@raphink better late than never, but if you haven't done it already you should give the version 0.3.0 a try, as it adds support for multiple service ports :)

**Comment by raphink** [comment]
I haven't yet, but I might will probably be interested in integrating this in our standard Kubernetes stack implementation soon.
