### ISSUE TITLE
API credentials Permissions

### ISSUE THREAD

**Issue by Vad1mo** [exoscale/exoscale-cloud-controller-manager#30]
What permission does the CCM need in particular in terms of the API?
It's not described in the docs. Is there a place where this detail can be looked up?

**Comment by mcorbin** [comment]
Here are the calls needed:

```
addServiceToLoadBalancer
createLoadBalancer
deleteLoadBalancer
deleteLoadBalancerService
listLoadBalancers
listVirtualMachines
queryAsyncJobResult
showLoadBalancerDetails
showLoadBalancerServiceDetails
updateLoadBalancer
updateLoadBalancerService
```

Note that on SKS, the CCM (and the associated IAM key) is now automatically managed on our side.

**Comment by Vad1mo** [comment]
Ow that’s new to me! we are on SKS. Could I get the latest documentation?

**Comment by mcorbin** [comment]
> Ow that’s new to me! we are on SKS. Could I get the latest documentation?

You should have been contacted directly by us with the latest information.

**Comment by falzm** [comment]
Closing this issue as it seems the questions pertaining to this project have been answered.
